version: '3.8'
services:
  db:
    container_name: pae-rh-db
    restart: always
    env_file: .env.development
    volumes:
      - pae-rh-dev-data:/var/lib/postgresql/data

  api:
    container_name: pae-rh-api-development
    restart: always
    env_file: .env.development
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    command: sh -c "poetry run alembic upgrade head && poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  pae-rh-dev-data:
    driver: local