# docker-compose.yml (BASE)
version: '3.8'
services:
  db:
    image: postgres:17-alpine
    # SIN container_name, restart, env_file, o volumes nombrados aquí
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  api:
    build: .
    # SIN container_name, restart, env_file, ports, o volumes de código aquí
    depends_on:
      db:
        condition: service_healthy